### ISSUE TITLE
オフライン時のAPI エラーハンドリング

### ISSUE THREAD

**Issue by YumNumm** [YumNumm/github-repository-search#3]
```log
10-22 17:06:15.764  4625  4647 I flutter : Source stack:
10-22 17:06:15.764  4625  4647 I flutter : #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
10-22 17:06:15.764  4625  4647 I flutter : #1      _RepositoryApiClient.fetch (package:github_repository_search/api/repository_api_client.g.dart:48)
10-22 17:06:15.764  4625  4647 I flutter : #2      GitHubRepository.fetch (package:github_repository_search/repository/github_repository.dart:21)
10-22 17:06:15.764  4625  4647 I flutter : #3      RepositorySearchViewModel.fetch.<anonymous closure> (package:github_repository_search/ui/page/search_view/search_view.viewmodel.dart:58)
10-22 17:06:15.764  4625  4647 I flutter : #4      AsyncValue.guard (package:riverpod/src/common.dart:145)
10-22 17:06:15.764  4625  4647 I flutter : #5      RepositorySearchViewModel.fetch (package:github_repository_search/ui/page/search_view/search_view.viewmodel.dart:55)
10-22 17:06:15.764  4625  4647 I flutter : #6      RepositorySearchFloatingActionButton.build.<anonymous closure> (package:github_repository_search/ui/page/search_view/component/repository_search_floating_action_button.dart:19)
10-22 17:06:15.764  4625  4647 I flutter : #7      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072)
10-22 17:06:15.764  4625  4647 I flutter : #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253)
10-22 17:06:15.764  4625  4647 I flutter : #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627)
10-22 17:06:15.764  4625  4647 I flutter : #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306)
10-22 17:06:15.764  4625  4647 I flutter : #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239)
10-22 17:06:15.764  4625  4647 I flutter : #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615)
10-22 17:06:15.764  4625  4647 I flutter : #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
10-22 17:06:15.764  4625  4647 I flutter : #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
10-22 17:06:15.764  4625  4647 I flutter : #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617)
10-22 17:06:15.764  4625  4647 I flutter : #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
10-22 17:06:15.764  4625  4647 I flutter : #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
10-22 17:06:15.764  4625  4647 I flutter : #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460)
10-22 17:06:15.764  4625  4647 I flutter : #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440)
10-22 17:06:15.764  4625  4647 I flutter : #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337)
10-22 17:06:15.764  4625  4647 I flutter : #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395)
10-22 17:06:15.764  4625  4647 I flutter : #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357)
10-22 17:06:15.764  4625  4647 I flutter : #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314)
10-22 17:06:15.764  4625  4647 I flutter : #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295)
10-22 17:06:15.764  4625  4647 I flutter : #25     _invoke1 (dart:ui/hooks.dart:167)
10-22 17:06:15.764  4625  4647 I flutter : #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341)
10-22 17:06:15.764  4625  4647 I flutter : #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)
```

**Comment by YumNumm** [comment]
d8a72167120118a373978ba6b526cc2b5cd9a593
